default:
  navigation:
    - title: Compra
      subtitle: Categorias
      url: /t/compra
      items:
        - :title: Tecnología
          :url: /t/compra/tecnologia
        - :title: Ropa
          :url: /t/compra/ropa
        - :title: Comida
          :url: /t/compra/comida
        - :title: Electrodomesticos
          :url: /t/compra/electrodomesticos
        - :title: Juguetes
          :url: /t/compra/juguetes
        - :title: Entretenimiento
          :url: /t/compra/entretenimiento
      promo_banners:
        - subtitle: Nueva iMac con chip M1
          title: Apple LLega a Merkadito
          url: /t/compra/tecnologia/laptops
          image: 'homepage/apple-m1.jpg'
        - subtitle: Ofertas de Verano
          title: Descuentos desde el 30%
          url: /t/compra
          image: 'homepage/promo-verano.jpg'
    - title: Vende
      subtitle: Vende en Merkadito
      url: /vender
      items:
        - :title: ¿Cómo vender con Merkadito?
          :url: /como-vender
        - :title: Políticas de Venta
          :url: /politicas-venta
        - :title: Registrarse como Proveedor
          :url: /registrar-proveedor
        - :title: Tablero de Ventas
          :url: /dashboard-proveedor
    - title: Sobre Nosotros
      subtitle: Nuestra Empresa
      url: /sobre-merkadito
      items:
        - :title: Quienes Somos
          :url: /sobre-merkadito#quienes-somos
        - :title: Misión
          :url: /sobre-merkadito#mision
        - :title: Visión
          :url: /sobre-merkadito#vision
      
fr:
  navigation:
    - title: Femmes
      url: /fr/t/women
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Hommes
      url: /fr/t/men
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Vêtements de sport
      url: /fr/t/sportswear
      promo_banners:
        - subtitle: Nouvelle collection
          title: Été 2021
          url: /fr/t/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Offres spéciales
          url: /fr/t/special-offers/30-percent-off
          image: 'meganav/promo_banner_right-third-category.jpg'
